batch_size: 128
epochs: 10
image_size: 224
loss_label_smoothing: 0
loss_weights: 1.0
lr_scheduler_T_0: 0
lr_scheduler_T_mult: 2
lr_scheduler_eta_min: 5.0e-07
maintain_image_aspect_ratio: true
model_arch_name: resnet50
model_ema_decay: 0.99998
model_lr: 0.0001
model_mean_parameters:
- 0.485
- 0.456
- 0.406
model_momentum: 0.9
model_std_parameters:
- 0.229
- 0.224
- 0.225
model_weight_decay: 0.0001
num_h0classes: 3
num_h1classes: 8
num_workers: 4
print_frequency: 50
use_albumentation: false
